"""Verified-chat adapter boundary for model calls and frozen replay artefacts."""

from adapters.extract import ExtractedPackBundle
from adapters.verified_chat.contracts import (
    ChatReference,
    FrozenReplayInputs,
    ModelResponse,
    ModelSelection,
    ModelSettings,
    ProviderKind,
    ReferenceKind,
    VerifiedChatRequest,
    VerifiedChatRun,
    verified_chat_run_path,
)
from adapters.verified_chat.replay import kernel_replay_inputs, load_verified_chat_run
from adapters.verified_chat.runner import (
    VerifiedChatArtifactPaths,
    VerifiedChatPipelineResult,
    build_and_persist_verified_chat_run,
    build_verified_chat_run,
    load_verified_chat_run_bundle,
    persist_verified_chat_run,
)
from adapters.verified_chat.storage import (
    load_verified_chat_cleaned_output,
    load_verified_chat_extracted_pack,
    load_verified_chat_request,
    load_verified_chat_response,
    load_verified_chat_run_at_root,
    save_verified_chat_cleaned_output,
    save_verified_chat_extracted_pack,
    save_verified_chat_request,
    save_verified_chat_response,
    save_verified_chat_run,
    save_verified_chat_run_at_root,
    verified_chat_cleaned_output_path,
    verified_chat_extracted_pack_path,
    verified_chat_request_path,
    verified_chat_response_path,
)

__all__ = [
    "ChatReference",
    "ExtractedPackBundle",
    "FrozenReplayInputs",
    "ModelResponse",
    "ModelSelection",
    "ModelSettings",
    "ProviderKind",
    "ReferenceKind",
    "VerifiedChatRequest",
    "VerifiedChatRun",
    "VerifiedChatArtifactPaths",
    "VerifiedChatPipelineResult",
    "build_and_persist_verified_chat_run",
    "build_verified_chat_run",
    "kernel_replay_inputs",
    "load_verified_chat_cleaned_output",
    "load_verified_chat_extracted_pack",
    "load_verified_chat_request",
    "load_verified_chat_response",
    "load_verified_chat_run",
    "load_verified_chat_run_at_root",
    "load_verified_chat_run_bundle",
    "persist_verified_chat_run",
    "save_verified_chat_run_at_root",
    "save_verified_chat_cleaned_output",
    "save_verified_chat_extracted_pack",
    "save_verified_chat_request",
    "save_verified_chat_response",
    "save_verified_chat_run",
    "verified_chat_run_path",
    "verified_chat_cleaned_output_path",
    "verified_chat_extracted_pack_path",
    "verified_chat_request_path",
    "verified_chat_response_path",
]
