"""Verified-chat adapter boundary for model calls and frozen replay artefacts."""

from adapters.extract import ExtractedPackBundle
from adapters.verified_chat.contracts import (
    ChatReference,
    FrozenReplayInputs,
    ModelResponse,
    ModelSelection,
    ModelSettings,
    ProviderKind,
    ReferenceKind,
    VerifiedChatRequest,
    VerifiedChatRun,
    verified_chat_run_path,
)
from adapters.verified_chat.extraction import extract_model_response_pack
from adapters.verified_chat.llm import (
    DeterministicStubLLMAdapter,
    GeminiHTTPAdapter,
    LLMAdapterError,
    UserOwnedHTTPAdapter,
    adapter_for_provider,
    model_response_for_text,
)
from adapters.verified_chat.replay import kernel_replay_inputs, load_verified_chat_run
from adapters.verified_chat.runner import (
    VerifiedChatArtifactPaths,
    VerifiedChatPipelineResult,
    build_and_persist_verified_chat_run,
    build_verified_chat_run,
    load_verified_chat_run_bundle,
    persist_verified_chat_run,
)
from adapters.verified_chat.service import (
    VerifiedChatLatestResponse,
    VerifiedChatRunRequest,
    VerifiedChatRunResponse,
    VerifiedChatService,
    VerifiedChatServiceConfig,
    create_verified_chat_http_server,
    run_verified_chat_http_service,
)
from adapters.verified_chat.storage import (
    load_verified_chat_cleaned_output,
    load_verified_chat_extracted_pack,
    load_verified_chat_request,
    load_verified_chat_response,
    load_verified_chat_run_at_root,
    save_verified_chat_cleaned_output,
    save_verified_chat_extracted_pack,
    save_verified_chat_request,
    save_verified_chat_response,
    save_verified_chat_run,
    save_verified_chat_run_at_root,
    verified_chat_cleaned_output_path,
    verified_chat_extracted_pack_path,
    verified_chat_request_path,
    verified_chat_response_path,
)

__all__ = [
    "ChatReference",
    "ExtractedPackBundle",
    "FrozenReplayInputs",
    "ModelResponse",
    "ModelSelection",
    "ModelSettings",
    "ProviderKind",
    "ReferenceKind",
    "VerifiedChatRequest",
    "VerifiedChatRun",
    "VerifiedChatArtifactPaths",
    "VerifiedChatLatestResponse",
    "VerifiedChatPipelineResult",
    "VerifiedChatRunRequest",
    "VerifiedChatRunResponse",
    "VerifiedChatService",
    "VerifiedChatServiceConfig",
    "DeterministicStubLLMAdapter",
    "GeminiHTTPAdapter",
    "LLMAdapterError",
    "UserOwnedHTTPAdapter",
    "adapter_for_provider",
    "build_and_persist_verified_chat_run",
    "build_verified_chat_run",
    "create_verified_chat_http_server",
    "extract_model_response_pack",
    "kernel_replay_inputs",
    "load_verified_chat_cleaned_output",
    "load_verified_chat_extracted_pack",
    "load_verified_chat_request",
    "load_verified_chat_response",
    "load_verified_chat_run",
    "load_verified_chat_run_at_root",
    "load_verified_chat_run_bundle",
    "persist_verified_chat_run",
    "model_response_for_text",
    "run_verified_chat_http_service",
    "save_verified_chat_run_at_root",
    "save_verified_chat_cleaned_output",
    "save_verified_chat_extracted_pack",
    "save_verified_chat_request",
    "save_verified_chat_response",
    "save_verified_chat_run",
    "verified_chat_run_path",
    "verified_chat_cleaned_output_path",
    "verified_chat_extracted_pack_path",
    "verified_chat_request_path",
    "verified_chat_response_path",
]
